// "Fix this" / "Fix my plan": deterministic suggestions. Pure, no React.
//
// Candidates are generated by search, never by AI: every free spot where the
// room fits inside the home without overlapping another room is re-scored by
// the same rules engine that rates the plan, and the best few are proposed.
// Nothing is applied until the user says so.

import type { Plan, Room, Wall, Zone } from "./types";
import { PLAN_DEFAULTS } from "./types";
import { analyzePlan, rateRoom, type RoomRating } from "./analysis";
import { bbox, brahmasthanRadius, fixtureFacing, planCenter, roomDirection, roomInsidePlot, roomsOverlap, screenBearing } from "./geometry";
import { DIR_BEARING } from "./lens";
import { getRule } from "./rules";

export type FixChange =
  | { kind: "move"; roomId: string; x: number; y: number }
  | { kind: "door"; roomId: string; fixtureId: string; wall: Wall };

export interface FixSuggestion {
  change: FixChange;
  roomId: string;
  roomType: string;
  fromZone: Zone;
  toZone: Zone;
  fromRating: RoomRating["ratingKey"];
  toRating: RoomRating["ratingKey"];
  scoreBefore: number;
  scoreAfter: number;
}

const RANK: Record<RoomRating["ratingKey"], number> = { ideal: 4, acceptable: 3, poor: 2, center: 1, harmful: 0 };

export function applyChange(plan: Plan, change: FixChange): Plan {
  return {
    ...plan,
    rooms: plan.rooms.map((r) => {
      if (r.id !== change.roomId) return r;
      if (change.kind === "move") return { ...r, x: change.x, y: change.y };
      return { ...r, fixtures: r.fixtures.map((f) => (f.id === change.fixtureId ? { ...f, wall: change.wall } : f)) };
    }),
  };
}

function fits(plan: Plan, room: Room, x: number, y: number): boolean {
  const moved = { ...room, x, y };
  if (!roomInsidePlot(moved, plan.plot)) return false;
  return plan.rooms.every((o) => o.id === room.id || !roomsOverlap(moved, o));
}

/**
 * Up to `limit` better placements for one room, best first, each in a
 * different direction. Empty when the room is already ideal or nothing fits.
 */
export function suggestFixes(plan: Plan, roomId: string, limit = 2): FixSuggestion[] {
  const room = plan.rooms.find((r) => r.id === roomId);
  if (!room || !getRule(room.type)) return [];
  const before = rateRoom(room, plan);
  if (before.ratingKey === "ideal") return [];
  const scoreBefore = analyzePlan(plan).overallScore;

  const base = { roomId, roomType: room.type, fromZone: before.zone, fromRating: before.ratingKey, scoreBefore };

  // An entrance is judged by its door: turn the door, don't move the room.
  const door = room.type === "entrance" ? room.fixtures.find((f) => f.kind === "door") : undefined;
  if (door) {
    const out: FixSuggestion[] = [];
    for (const wall of ["top", "right", "bottom", "left"] as Wall[]) {
      if (wall === door.wall) continue;
      const change: FixChange = { kind: "door", roomId, fixtureId: door.id, wall };
      const next = applyChange(plan, change);
      const after = rateRoom(next.rooms.find((r) => r.id === roomId)!, next);
      if (RANK[after.ratingKey] <= RANK[before.ratingKey]) continue;
      out.push({ ...base, change, toZone: fixtureFacing(wall, plan), toRating: after.ratingKey, scoreAfter: analyzePlan(next).overallScore });
    }
    return out.sort((a, b) => RANK[b.toRating] - RANK[a.toRating] || b.scoreAfter - a.scoreAfter).slice(0, limit);
  }

  const bb = bbox(plan.plot);
  const span = Math.max(bb.w, bb.h);
  const c = planCenter(plan);
  const keepClear = brahmasthanRadius(plan) * 2.2;
  // Lower is better: how far off the zone's heart the room sits (0..1), how far it moves,
  // minus a bonus for sitting out towards the walls.
  const cost = (x: number, y: number, zone: Zone) => {
    const cx = x + room.w / 2 - c.x;
    const cy = y + room.h / 2 - c.y;
    const real = (screenBearing(cx, cy) + plan.northOffsetDeg) % 360;
    const target = zone === "C" ? real : DIR_BEARING[zone];
    const off = Math.abs((((real - target) % 360) + 540) % 360 - 180) / 22.5;
    // Rooms read naturally against the outer walls, deep in their zone.
    const outward = Math.hypot(cx, cy) / (span / 2);
    return off * 2 + Math.hypot(x - room.x, y - room.y) / span - outward * 0.6;
  };
  const step = span > 24 ? 1 : PLAN_DEFAULTS.gridU;
  // Best candidate per direction.
  const best = new Map<Zone, { x: number; y: number; rank: number; score: number; dist: number; rating: RoomRating["ratingKey"] }>();
  // "dist" below is the placement cost: off-centre in its zone + length of the move.
  for (let x = bb.minX; x <= bb.maxX - room.w + 1e-9; x += step) {
    for (let y = bb.minY; y <= bb.maxY - room.h + 1e-9; y += step) {
      const zone = roomDirection({ ...room, x, y }, plan);
      const moved = { ...room, x, y };
      const rating = rateRoom(moved, plan).ratingKey;
      const rank = RANK[rating];
      if (rank <= RANK[before.ratingKey]) continue;
      // Stay well clear of the centre: a room hugging the Brahmasthan reads as the wrong zone.
      if (Math.hypot(x + room.w / 2 - c.x, y + room.h / 2 - c.y) < keepClear) continue;
      const cur = best.get(zone);
      const dist = cost(x, y, zone);
      if (cur && cur.rank >= rank && cur.dist <= dist) continue;
      if (!fits(plan, room, x, y)) continue;
      const next = applyChange(plan, { kind: "move", roomId, x, y });
      const score = analyzePlan(next).overallScore;
      if (!cur || rank > cur.rank || score > cur.score || (score === cur.score && dist < cur.dist)) {
        best.set(zone, { x, y, rank, score, dist, rating });
      }
    }
  }

  return [...best.entries()]
    .sort(([, a], [, b]) => b.rank - a.rank || b.score - a.score || a.dist - b.dist)
    .slice(0, limit)
    .map(([zone, c]) => ({
      ...base,
      change: { kind: "move", roomId, x: Math.round(c.x * 2) / 2, y: Math.round(c.y * 2) / 2 },
      toZone: zone,
      toRating: c.rating,
      scoreAfter: c.score,
    }));
}

export interface PlanFix {
  steps: FixSuggestion[];
  plan: Plan;
  scoreBefore: number;
  scoreAfter: number;
}

/**
 * "Fix my plan": improve room by room, worst and most important first, keeping
 * only moves that raise the overall score. Each step is re-planned against the
 * plan as changed so far, so later moves never collide with earlier ones.
 */
export function planFixes(plan: Plan, maxSteps = 6): PlanFix {
  const scoreBefore = analyzePlan(plan).overallScore;
  let cur = plan;
  const steps: FixSuggestion[] = [];
  const tried = new Set<string>();
  for (let i = 0; i < maxSteps; i++) {
    const ranked = analyzePlan(cur)
      .rooms.filter((r) => r.ratingKey !== "ideal" && !tried.has(r.roomId))
      .sort((a, b) => RANK[a.ratingKey] - RANK[b.ratingKey] || (getRule(b.roomType)?.weight ?? 0) - (getRule(a.roomType)?.weight ?? 0));
    let applied = false;
    for (const r of ranked) {
      tried.add(r.roomId);
      const [s] = suggestFixes(cur, r.roomId, 1);
      if (s && s.scoreAfter > s.scoreBefore) {
        steps.push(s);
        cur = applyChange(cur, s.change);
        applied = true;
        break;
      }
    }
    if (!applied) break;
  }
  return { steps, plan: cur, scoreBefore, scoreAfter: analyzePlan(cur).overallScore };
}
