/**
 * Legal documents — Terms of Service, Privacy Policy, Astrology Disclaimer.
 *
 * The legal body is intentionally English-only: under Indian contract practice
 * a single governing-language text avoids enforceability disputes between
 * translations. Page chrome (titles, nav) is translated via i18n; a translated
 * banner on each page states that the English text governs. DPDP Act §5(3)
 * contemplates notices in Eighth Schedule languages — professionally reviewed
 * translations can be added later without changing this structure.
 *
 * LEGAL_VERSION is what onboarding stamps into each consent record — it now
 * imports this constant rather than restating the literal, because the two
 * had already drifted apart once. The backend's GET /legal/current still
 * hardcodes 1.0.0 and needs the same bump; note also that nothing currently
 * re-prompts existing users when the version changes, so consent records
 * naming an older version are expected until a re-consent gate exists.
 *
 * Legal entity (Aroha Astrology), registered office (Bangalore, India), and
 * the named Grievance Officer (Subir Dutta, subir@arohaastrology.in) are
 * filled in below. The whole text should be reviewed by qualified Indian
 * counsel — it is a considered draft, not legal advice.
 */

export const LEGAL_VERSION = "1.1.0";
export const LEGAL_UPDATED = "20 July 2026";

export interface LegalSection {
  heading: string;
  paragraphs: string[];
}

export interface LegalDoc {
  slug: "terms" | "privacy" | "disclaimer";
  title: string;
  intro: string;
  sections: LegalSection[];
}

/* ────────────────────────────────────────────────────────────────────────── */
/* Terms of Service                                                           */
/* ────────────────────────────────────────────────────────────────────────── */

export const TERMS: LegalDoc = {
  slug: "terms",
  title: "Terms of Service",
  intro:
    "These Terms of Service (“Terms”) are an electronic record under the Information Technology Act, 2000 and the rules made thereunder, and constitute a legally binding agreement between you and Aroha Astrology, having its registered office at Bangalore, India (“Aroha”, “we”, “us”). By creating an account or using the Aroha Astrology application and services (the “Service”), you accept these Terms. This electronic record does not require a physical or digital signature (Section 10A, IT Act, 2000).",
  sections: [
    {
      heading: "1. Eligibility",
      paragraphs: [
        "You must be at least 18 years of age to use the Service. The Service processes personal data under consent; the Digital Personal Data Protection Act, 2023 (“DPDP Act”) requires verifiable parental consent for persons under 18, which the Service does not currently support. By using the Service you represent that you are 18 or older.",
      ],
    },
    {
      heading: "2. Nature of the Service",
      paragraphs: [
        "Aroha provides Vedic astrology content — birth charts (kundli), panchang, horoscopes, compatibility matching, and conversational readings — computed from the birth details you provide and, in part, generated by artificial-intelligence systems.",
        "Astrology is a traditional belief system. The Service is offered for spiritual, cultural, and informational guidance only. It is not a scientific instrument, and nothing in the Service is a prediction, promise, or guarantee of any outcome, event, or result.",
      ],
    },
    {
      heading: "3. No Professional Advice",
      paragraphs: [
        "Content from the Service (including AI chat responses, horoscopes, remedies, and match reports) is not medical, psychological, legal, financial, or investment advice, and must not be used as a substitute for consultation with qualified professionals. Never disregard professional advice or delay seeking it because of anything read on the Service.",
        "Suggested remedies (gemstones, rituals, mantras, and similar) are traditional practices shared for cultural and spiritual interest. We make no claim — and you should infer none — that any remedy cures, treats, or prevents any disease or condition, or produces any material outcome. We do not make claims of the kind restricted by the Drugs and Magic Remedies (Objectionable Advertisements) Act, 1954.",
      ],
    },
    {
      heading: "4. AI-Generated Content",
      paragraphs: [
        "Parts of the Service are generated by AI language models grounded in your computed chart. AI output can be incomplete, imprecise, or wrong, and may vary between sessions. It reflects astrological interpretation, not verified fact, and is provided “as is”.",
      ],
    },
    {
      heading: "5. Your Account and Responsibilities",
      paragraphs: [
        "You agree to provide accurate birth details — readings are computed directly from them — and to keep your phone number and OTPs secure. You are responsible for activity under your account.",
        "You agree not to misuse the Service: no unlawful, defamatory, or infringing content; no attempts to probe, overload, reverse-engineer, or disrupt the Service; no scraping or bulk extraction; no impersonation.",
      ],
    },
    {
      heading: "6. Birth Details of Other Persons",
      paragraphs: [
        "Features such as compatibility matching let you submit another person's name and birth details. You must do so only with that person's knowledge and consent (or, for a minor, their guardian's consent). You confirm you are authorised to share such details, and you indemnify us against claims arising from details you were not entitled to share.",
      ],
    },
    {
      heading: "7. Payments and Refunds",
      paragraphs: [
        "Parts of the Service may be offered for a fee. Prices, inclusions, and billing terms are shown before purchase. Except where required by law (including the Consumer Protection Act, 2019 and the Consumer Protection (E-Commerce) Rules, 2020), fees for digital content already delivered are non-refundable. Statutory rights you hold as a consumer under Indian law are not affected by these Terms.",
      ],
    },
    {
      heading: "8. Intellectual Property",
      paragraphs: [
        "The Service — including software, design, text, charts, and branding — is owned by or licensed to Aroha and protected under Indian copyright and trademark law. We grant you a personal, non-exclusive, non-transferable licence to use the Service for personal, non-commercial purposes. Your birth details remain yours; you grant us the licence needed to process them to provide the Service, as described in the Privacy Policy.",
      ],
    },
    {
      heading: "9. Suspension and Termination",
      paragraphs: [
        "We may suspend or terminate access for breach of these Terms, unlawful use, or risk to the Service or other users. You may stop using the Service and delete your account at any time from within the app; deletion is handled as described in the Privacy Policy.",
      ],
    },
    {
      heading: "10. Limitation of Liability",
      paragraphs: [
        "To the maximum extent permitted by Indian law, Aroha shall not be liable for indirect, incidental, or consequential loss, or for decisions taken in reliance on astrological or AI-generated content. Our total aggregate liability for any claim relating to the Service shall not exceed the amount you paid us in the six months preceding the claim (or ₹1,000 if you paid nothing). Nothing in these Terms limits liability that cannot be limited under Indian law.",
      ],
    },
    {
      heading: "11. Privacy",
      paragraphs: [
        "Personal data is processed as described in the Privacy Policy, which forms part of these Terms and reflects our obligations under the DPDP Act, 2023 and the IT Act, 2000 (including the SPDI Rules, 2011).",
      ],
    },
    {
      heading: "12. Changes to These Terms",
      paragraphs: [
        "We may revise these Terms. Material changes will be notified in the app, and the version number and date above will change. Continued use after the effective date constitutes acceptance; if you do not agree, stop using the Service and delete your account.",
      ],
    },
    {
      heading: "13. Governing Law and Jurisdiction",
      paragraphs: [
        "These Terms are governed by the laws of India. Subject to any mandatory consumer-protection forum available to you, the courts at Bangalore, Karnataka, India shall have exclusive jurisdiction.",
      ],
    },
    {
      heading: "14. Grievance Redressal",
      paragraphs: [
        "For complaints or grievances about the Service or these Terms, contact us at: subir@arohaastrology.in. We acknowledge grievances within 72 hours and aim to resolve them within 15 working days, consistent with the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 and the DPDP Act, 2023.",
      ],
    },
  ],
};

/* ────────────────────────────────────────────────────────────────────────── */
/* Privacy Policy                                                             */
/* ────────────────────────────────────────────────────────────────────────── */

export const PRIVACY: LegalDoc = {
  slug: "privacy",
  title: "Privacy Policy",
  intro:
    "This Privacy Policy is the notice required under Section 5 of the Digital Personal Data Protection Act, 2023 (“DPDP Act”). Aroha Astrology, registered office Bangalore, India, is the Data Fiduciary for personal data processed through the Aroha Astrology application (the “Service”). It also reflects reasonable security practices under Section 43A of the IT Act, 2000 and the SPDI Rules, 2011.",
  sections: [
    {
      heading: "1. Personal Data We Collect",
      paragraphs: [
        "Account data: mobile phone number (verified by OTP), display name, gender.",
        "Birth data: date of birth, exact time of birth, place of birth including geographic coordinates and timezone. Because readings are computed from it, this is the core data the Service needs.",
        "Third-party birth profiles: name and birth details of another person that you submit for compatibility matching — only to be provided with that person's consent.",
        "Device location: if you grant the location permission, we collect your device's approximate location — city-level only; we never request high-accuracy or background location, and we do not track your movements. It is used while the app is open, and the location recorded at onboarding is stored on your profile as your current location until you delete your account. This is separate from your place of birth, which you enter yourself. Location is optional: you may decline the permission, or revoke it later in your device settings, and the Service continues to work — location-aware features such as local panchang timings simply fall back to a default reference location.",
        "Usage data: chat messages you send to the AI astrologer, feature usage, preferences (language, ayanamsa, house system), and technical logs (device type, approximate region, timestamps).",
      ],
    },
    {
      heading: "2. Purposes of Processing",
      paragraphs: [
        "We process personal data to: compute your kundli, dasha, panchang, and horoscopes; generate personalised AI readings and chat responses; run compatibility matching you request; operate, secure, and debug the Service; send service notifications you opt into; and meet legal obligations. We do not sell personal data, and we do not use it for third-party advertising.",
        "Device location, where you grant it, is used only to localise time-sensitive astrological calculations — panchang timings, sunrise and sunset, and transit readings are all specific to where you are — and to name that place back to you in the interface. We do not use location for advertising, profiling, or tracking, and we do not share it with data brokers.",
      ],
    },
    {
      heading: "3. Legal Basis — Your Consent",
      paragraphs: [
        "We process your personal data on the basis of consent (Section 6, DPDP Act), collected at onboarding through a free, specific, informed, and unambiguous affirmative action. You may withdraw consent at any time in Settings or by deleting your account; withdrawal stops future processing but does not affect processing already carried out. Some features (chart, horoscope, chat, matching) cannot function without the birth data they compute from — withdrawing consent for that data means those features stop working.",
      ],
    },
    {
      heading: "4. How Processing Works",
      paragraphs: [
        "Chart mathematics run on our servers using astronomical (ephemeris) calculations. Narrative content is generated by AI language models that receive your computed chart context (and your chat messages) to produce a response. Consent events are recorded in an append-only audit log with timestamps and document versions, as the DPDP Act's accountability provisions contemplate.",
      ],
    },
    {
      heading: "5. Sharing and Data Processors",
      paragraphs: [
        "We share personal data only with processors who operate the Service under contract and on our instructions: cloud hosting and database providers, Google Firebase (phone authentication), and AI inference providers that process chart context and chat text to generate responses. Processors are not permitted to use your data for their own purposes.",
        "One exception is disclosed for completeness: when you grant location, your coordinates are sent to the OpenStreetMap Nominatim service to convert them into a place name for display. That is a public lookup service used without an account, not a contracted processor, and it receives coordinates only — never your identity, phone number, or birth details.",
        "Some processors may store or process data outside India. Such transfers are made in accordance with Section 16 of the DPDP Act (which permits transfers except to countries restricted by the Central Government) and with contractual safeguards.",
        "We may disclose personal data where required by Indian law or lawful government request.",
      ],
    },
    {
      heading: "6. Retention and Deletion",
      paragraphs: [
        "We retain personal data while your account is active. When you delete your account in the app, your profile and any third-party birth profiles you created are deactivated immediately and no longer used for any processing, and are then permanently erased from active systems within 30 days, except where a longer statutory retention applies (e.g. payment and tax records). Backup copies purge on their own rotation cycle.",
      ],
    },
    {
      heading: "7. Your Rights (DPDP Act, Sections 11–14)",
      paragraphs: [
        "You have the right to: access a summary of your personal data and the processing done on it; correct and update it (your profile is editable in the app); erase it (delete your account, or write to us); a readily available grievance mechanism (Section 14 below); and nominate another individual to exercise your rights if you die or are incapacitated.",
        "You also have duties under Section 15 of the DPDP Act, including not to impersonate another person or suppress material information when providing data.",
      ],
    },
    {
      heading: "8. Children",
      paragraphs: [
        "The Service is for users 18 and over. We do not knowingly process the personal data of children as defined by the DPDP Act. If you believe a minor has created an account, contact the Grievance Officer and we will delete it.",
      ],
    },
    {
      heading: "9. Security",
      paragraphs: [
        "We follow reasonable security practices under Section 43A of the IT Act, 2000: encryption in transit, access controls, authenticated APIs, and audit logging. No system is perfectly secure; in the event of a personal data breach we will notify the Data Protection Board of India and affected users as required by Section 8(6) of the DPDP Act.",
      ],
    },
    {
      heading: "10. Grievances and the Data Protection Board",
      paragraphs: [
        "Grievance Officer: Subir Dutta, email subir@arohaastrology.in, address Bangalore, India. We acknowledge within 72 hours and aim to resolve within 15 working days. If you are unsatisfied after exhausting this mechanism, you may complain to the Data Protection Board of India under the DPDP Act.",
      ],
    },
    {
      heading: "11. Changes to This Policy",
      paragraphs: [
        "We may update this Policy. Material changes will be notified in the app; where the change expands the purposes of processing, we will seek fresh consent as the DPDP Act requires. The version and date above always reflect the current text.",
      ],
    },
  ],
};

/* ────────────────────────────────────────────────────────────────────────── */
/* Astrology & AI Disclaimer                                                  */
/* ────────────────────────────────────────────────────────────────────────── */

export const DISCLAIMER: LegalDoc = {
  slug: "disclaimer",
  title: "Astrology & AI Disclaimer",
  intro:
    "This disclaimer applies to all content in the Aroha Astrology application — charts, horoscopes, panchang, compatibility reports, remedies, and AI astrologer conversations.",
  sections: [
    {
      heading: "1. Astrology Is a Belief System",
      paragraphs: [
        "Vedic astrology is a traditional practice and system of belief. Its content is offered for spiritual, cultural, and informational purposes. It is not science, and no reading is a prediction, promise, or guarantee of any event, outcome, or result.",
      ],
    },
    {
      heading: "2. Not Professional Advice",
      paragraphs: [
        "Nothing in the Service is medical, psychological, legal, financial, investment, or other professional advice. Decisions about health, money, relationships, career, or legal matters should be made with qualified professionals. Never disregard or delay professional advice because of a reading.",
      ],
    },
    {
      heading: "3. Remedies",
      paragraphs: [
        "Gemstones, rituals, mantras, and other suggested remedies are traditional practices shared for cultural interest. They are not treatments and are not claimed to cure, prevent, or mitigate any disease or condition (Drugs and Magic Remedies (Objectionable Advertisements) Act, 1954), nor to produce any material result. Consult a doctor for health concerns.",
      ],
    },
    {
      heading: "4. AI-Generated Content",
      paragraphs: [
        "AI responses are generated by language models interpreting your computed chart. They can be wrong, incomplete, or inconsistent, and do not represent the views of any human astrologer. Use your own judgment.",
      ],
    },
    {
      heading: "5. Personal Responsibility",
      paragraphs: [
        "You remain solely responsible for decisions and actions taken after using the Service. To the maximum extent permitted by Indian law, Aroha accepts no liability for reliance placed on astrological or AI-generated content.",
      ],
    },
  ],
};

export const LEGAL_DOCS: Record<LegalDoc["slug"], LegalDoc> = {
  terms: TERMS,
  privacy: PRIVACY,
  disclaimer: DISCLAIMER,
};
