// Regenerate all queue-driven AI content for one user using the CURRENT
// process.env.NVIDIA_NIM_MODEL. Designed to be run after a model swap.
//
// Strategy:
//   1. feature_insights (lite_ai source)
//        → enqueue `feature_lite` jobs. runLite calls upsert_feature_insight
//          which allows same-source overwrite. No delete needed; old rows stay
//          in place until each new run completes.
//   2. life_area_insights + life_journey_insights
//        → runLifeAreas/runLifeJourneyPhase are idempotent (skip when rows
//          exist). DELETE first, then enqueue ONE `life_journey_phase` job
//          per distinct (chart_id, phase_index). LJI is generated lazily on
//          user click — deleting is enough; next view regens with new model.
//   3. Skip date-keyed daily features (personal_daily, predictions_daily) —
//      they regen tomorrow on the next cron tick with the new model.
//
// Cron drains generation_queue every minute on Vercel. This script can also
// trigger an immediate drain via /api/queue/drain (uses INTERNAL_PROCESS_KEY).
//
// Usage:
//   node --env-file=apps/web/.env.local apps/web/scripts/regen-user-ai.mjs \
//     --phone=+919535960988 [--dry] [--no-kick] [--wait]
//
// Flags:
//   --dry      : print plan, don't write
//   --no-kick  : don't trigger the drain endpoint (cron will pick up within 60s)
//   --wait     : poll the queue until all enqueued jobs reach a terminal state

import { createClient } from '@supabase/supabase-js';

const args = process.argv.slice(2);
const flagVal = (name) => {
  const a = args.find((x) => x === `--${name}` || x.startsWith(`--${name}=`));
  if (!a) return undefined;
  const i = a.indexOf('=');
  return i >= 0 ? a.slice(i + 1) : true;
};

const phone   = flagVal('phone');
const userArg = flagVal('user');
const dry     = !!flagVal('dry');
const noKick  = !!flagVal('no-kick');
const wait    = !!flagVal('wait');

if (!phone && !userArg) {
  console.error('Pass --phone=+91... or --user=<uuid>');
  process.exit(1);
}

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_KEY  = process.env.SUPABASE_SERVICE_ROLE_KEY;
const INTERNAL_KEY = process.env.INTERNAL_PROCESS_KEY;
const WEB_BASE     = process.env.WEB_BASE_URL ?? 'https://www.arohaastrology.in';

if (!SUPABASE_URL || !SERVICE_KEY) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
});

// Features NOT in LITE_CALLS — runLite will no-op. Date-keyed daily features
// are regenerated by their own cron jobs.
const SKIP_FEATURE_KEYS = new Set(['personal_daily', 'predictions_daily']);

// ── Resolve user ────────────────────────────────────────────────────────────
let userId = userArg;
if (phone) {
  const { data } = await supabase
    .from('users').select('id, name, phone, language')
    .eq('phone', phone).maybeSingle();
  if (!data) { console.error(`No user with phone ${phone}`); process.exit(2); }
  userId = data.id;
  console.log(`▶ User: ${data.name ?? '(no name)'} ${phone} ${userId}`);
}

const currentModel = process.env.NVIDIA_NIM_MODEL ?? '(default mistral-nemotron)';
console.log(`▶ Target model: ${currentModel}`);
if (dry) console.log('▶ DRY RUN — no writes\n');

// ── 1. Plan feature_insights regen ──────────────────────────────────────────
const { data: fi } = await supabase
  .from('feature_insights')
  .select('chart_id, feature_key, params_hash, language, source')
  .eq('user_id', userId);

const liteJobsToEnqueue = (fi ?? [])
  .filter(r => r.source === 'lite_ai' && !SKIP_FEATURE_KEYS.has(r.feature_key))
  .map(r => ({
    chart_id:    r.chart_id,
    feature_key: r.feature_key,
    params_hash: r.params_hash ?? '',
    language:    r.language ?? 'en',
  }));

console.log(`\n═══ FEATURE_INSIGHTS ════════════════════════════════════════════`);
console.log(`  Total rows         : ${(fi ?? []).length}`);
console.log(`  Will regen (lite_ai): ${liteJobsToEnqueue.length}`);
console.log(`  Skipping (daily)   : ${(fi ?? []).filter(r => SKIP_FEATURE_KEYS.has(r.feature_key)).length}`);
console.log(`  Skipping (other src): ${(fi ?? []).filter(r => r.source !== 'lite_ai').length}`);

// ── 2. Plan life_area + life_journey deletions ──────────────────────────────
const { data: lai } = await supabase
  .from('life_area_insights')
  .select('chart_id, phase_index')
  .eq('user_id', userId);

const phasesToRegen = new Map();
for (const r of lai ?? []) {
  phasesToRegen.set(`${r.chart_id}|${r.phase_index}`, { chart_id: r.chart_id, phase_index: r.phase_index });
}

const { data: lji } = await supabase
  .from('life_journey_insights')
  .select('chart_id')
  .eq('user_id', userId);
const ljiChartIds = new Set((lji ?? []).map(r => r.chart_id));

console.log(`\n═══ LIFE JOURNEY ════════════════════════════════════════════════`);
console.log(`  life_area_insights rows    : ${(lai ?? []).length}`);
console.log(`  life_journey_insights rows : ${(lji ?? []).length}`);
console.log(`  Phases to regen            : ${phasesToRegen.size}`);
console.log(`  LJI charts to clear (lazy) : ${ljiChartIds.size}`);

if (dry) { console.log('\n✓ DRY plan complete — no writes performed'); process.exit(0); }

// ── 3. Execute: delete LAI rows, enqueue phase jobs ─────────────────────────
console.log(`\n▶ Writing...`);

let deletedLai = 0, deletedLji = 0;
for (const { chart_id, phase_index } of phasesToRegen.values()) {
  const { count } = await supabase
    .from('life_area_insights')
    .delete({ count: 'exact' })
    .eq('user_id', userId)
    .eq('chart_id', chart_id)
    .eq('phase_index', phase_index);
  deletedLai += count ?? 0;
}
for (const chart_id of ljiChartIds) {
  const { count } = await supabase
    .from('life_journey_insights')
    .delete({ count: 'exact' })
    .eq('user_id', userId)
    .eq('chart_id', chart_id);
  deletedLji += count ?? 0;
}
console.log(`  Deleted life_area_insights    : ${deletedLai}`);
console.log(`  Deleted life_journey_insights : ${deletedLji} (lazy regen on next view)`);

// ── 4. Enqueue jobs (raw insert; bypass the unique-pending index by clearing
//     any leftover open jobs for these payload tuples first). ───────────────
let enqueuedPhase = 0, enqueuedLite = 0, dedupSkipped = 0;

for (const p of phasesToRegen.values()) {
  // Close any stuck open jobs for this exact payload so the unique partial
  // index doesn't block our fresh insert.
  await supabase
    .from('generation_queue')
    .update({ status: 'skipped', completed_at: new Date().toISOString() })
    .eq('user_id', userId)
    .eq('job_type', 'life_journey_phase')
    .in('status', ['pending', 'processing'])
    .eq('payload->>chart_id', p.chart_id)
    .eq('payload->>phase_index', String(p.phase_index));

  const { error } = await supabase.from('generation_queue').insert({
    user_id: userId, job_type: 'life_journey_phase',
    payload: { chart_id: p.chart_id, phase_index: p.phase_index },
    priority: 5, status: 'pending',
  });
  if (error) {
    if (error.code === '23505') dedupSkipped++;
    else console.warn(`  ! enqueue phase ${p.phase_index} failed:`, error.message);
  } else enqueuedPhase++;
}

for (const j of liteJobsToEnqueue) {
  await supabase
    .from('generation_queue')
    .update({ status: 'skipped', completed_at: new Date().toISOString() })
    .eq('user_id', userId)
    .eq('job_type', 'feature_lite')
    .in('status', ['pending', 'processing'])
    .eq('payload->>chart_id', j.chart_id)
    .eq('payload->>feature_key', j.feature_key);

  const { error } = await supabase.from('generation_queue').insert({
    user_id: userId, job_type: 'feature_lite',
    payload: j, priority: -1, status: 'pending',
  });
  if (error) {
    if (error.code === '23505') dedupSkipped++;
    else console.warn(`  ! enqueue ${j.feature_key} failed:`, error.message);
  } else enqueuedLite++;
}

console.log(`  Enqueued life_journey_phase   : ${enqueuedPhase}`);
console.log(`  Enqueued feature_lite         : ${enqueuedLite}`);
console.log(`  Dedup-skipped                 : ${dedupSkipped}`);

// ── 5. Kick the drain (fire-and-forget) ─────────────────────────────────────
if (!noKick && INTERNAL_KEY) {
  console.log(`\n▶ Kicking drain at ${WEB_BASE}/api/queue/drain ...`);
  try {
    const res = await fetch(`${WEB_BASE}/api/queue/drain`, {
      method: 'POST',
      headers: { 'x-internal-key': INTERNAL_KEY, 'Content-Type': 'application/json' },
      body: JSON.stringify({ source: 'regen-user-ai' }),
    });
    console.log(`  drain HTTP ${res.status}`);
    const body = await res.text().catch(() => '');
    if (body) console.log(`  ${body.slice(0, 200)}`);
  } catch (e) {
    console.warn(`  ! drain kick failed: ${e.message}. Cron will pick up within ~60s.`);
  }
} else if (!INTERNAL_KEY) {
  console.log(`\n⚠ INTERNAL_PROCESS_KEY not set — cron will drain on its own (~60s).`);
}

// ── 6. Optional wait+poll ───────────────────────────────────────────────────
if (wait) {
  console.log(`\n▶ Polling queue every 5s until all enqueued jobs finish...\n`);
  const total = enqueuedPhase + enqueuedLite;
  const started = Date.now();
  while (Date.now() - started < 10 * 60_000) {
    const { count: openCount } = await supabase
      .from('generation_queue')
      .select('*', { count: 'exact', head: true })
      .eq('user_id', userId)
      .in('status', ['pending', 'processing'])
      .gte('created_at', new Date(started - 30_000).toISOString());
    const done = total - (openCount ?? 0);
    process.stdout.write(`\r  ${done}/${total} done · ${openCount ?? '?'} open · ${Math.floor((Date.now() - started) / 1000)}s`);
    if ((openCount ?? 0) === 0) break;
    await new Promise(r => setTimeout(r, 5000));
  }
  console.log('\n  ✓ All jobs settled (or 10-min timeout).');
}

console.log(`\n✓ Done. Old rows stay in place until each new gen overwrites them; LJI regens lazily on next view.`);
